### ISSUE TITLE
Any support for ssl & ssl certs?

### ISSUE THREAD

**Issue by chaodoze** [davesag/sequelize-pg-utilities#28]
or plans to support?

**Comment by davesag** [comment]
@chaodoze would you mind spelling out in more detail what you want?

**Comment by davesag** [comment]
I'm looking at https://github.com/sequelize/sequelize/issues/956 but that's quite an old issue. I am using this library in production on projects running on Heroku without any special config on my end, though I do recall some config needed to be done at the Heroku end.

Anyway please get back to me with more details and I am happy to look into this further for you.

**Comment by chaodoze** [comment]
Dave, thanks for you reply and attention to this issue. Currently, on
vacation so will have a more thoughtful reply tomorrow. Basically, I’m
looking to connect to a Postgres SQL server via ssl. Node-postgres offers
this config setup:
https://node-postgres.com/features/ssl

Wondering if this package has a way to piggy back on that. Thanks!

**Comment by davesag** [comment]
Hi @chaodoze that's interesting.  Under the hood I am using [`pgtools`](https://github.com/olalonde/pgtools) to handle the creation of the database, but am simply using [`sequelize`](https://github.com/sequelize/sequelize) to actually connect to it once the database has been created.  My library just formats the config correctly for either to use.

Assuming your database is running in production when secured you probably won't need to use the `makeInitialiser` feature I provide (which is the bit that uses `pgtools`) but you will need to pass ssl configuration options through to sequelize. (Note if you are not using `sequelize` then you don't need this library at all).

It looks like I could just take the `ssl` block from config and pass it through as [`dialectOptions`](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L63).  I'd be willing to try that as a test-release and you could check to see if that does what you need.  If it does then I'd also probably have to refactor the `makeInitialiser` function to not use `pgtools`.

So one step at a time perhaps.

I'm also on vacation right now (we Australians get a 4 day break for easter) but I am not doing much other than loll about by the hotel pool, so will spend a bit more time having a look at this.

**Comment by davesag** [comment]
Hi @chaodoze This feature is now available in version `1.2.0` — thanks for your suggestion.
