### ISSUE TITLE
DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.

### ISSUE THREAD

**Issue by davesag** [davesag/sequelize-pg-utilities#35]
Check for Sequelize v5 and don't pass in `operatorsAliases` option if detected.

**Comment by hamedkaka** [comment]
hi 
try
operatorsAliases: true,
on 
operatorsAliases: 1,

**Comment by Imran-Haider313** [comment]
I don't think that's a solution. A better to handle it is [This post](https://stackoverflow.com/questions/58593200/deprecationwarning-a-boolean-value-was-passed-to-options-operatorsaliases-this)

**Comment by davesag** [comment]
> I don't think that's a solution. A better to handle it is [This post](https://stackoverflow.com/questions/58593200/deprecationwarning-a-boolean-value-was-passed-to-options-operatorsaliases-this)

Thanks I’ll take a look.

**Comment by davesag** [comment]
Having read through [the latest version of the docs](https://sequelize.org/master/manual/model-querying-basics.html) I have decided to remove the `operatorsAliases` option completely.

> Deprecated: Operator Aliases

> In Sequelize v4, it was possible to specify strings to refer to operators, instead of using Symbols. This is now deprecated and heavily discouraged, and will probably be removed in the next major version.

**Comment by SuzanBudha** [comment]
f
